### ISSUE TITLE
path sbagliati

### ISSUE THREAD

**Issue by nemesifier** [ninuxorg/nodogsplashninux#2]
il css punta a "images/[nomefile]". E' sbagliato perchè il css è stato spostato nella stessa cartella dove ci sono le immagini.

Sto correggendo nel mio fork.

**Comment by nemesifier** [comment]
@gubi leggi

ho scaricato il repository e ho provato file. Dopo aver aggiornato i vari path nel codice html e css per fargli trovare i file che non trovava più ho notato che l'aspetto della pagina è diverso rispetto alla versione che ho scaricato direttamente da gubi.

Gubi riesci a correggere questo problema?

**Comment by gubi** [comment]
Se lo provi in locale è normale che ti da problemi coi path.
Ciò che è caricato è stato testato direttamente su un HotSpot.
NoDog ha come cartella predefinita la variabile $imagesdir che equivale a "images/" e non ho trovato la maniera di cambiarla.

**Comment by nemesifier** [comment]
@gubi non sono scemo eh! Ho fatto un file index.html che uso solo per testing dove ho rimpiazzato $imagesdir con il path giusto, tuttavia la pagina ha un aspetto diverso. Puoi dargli un occhiata? Ho fatto una pull request qui, aspettiamo che @zioproto o @claudyus la accettano, ah forse ho sbagliato dovevo farla sul branch minification.

**Comment by gubi** [comment]
@nemesisdesign lo so che non sei scemo, ma una svista può sempre capitare :)
Dove vado a vedere? Io continuo a dire che scaricata così com'è e caricata sul mio device (PicoStation M2HP) funziona...

**Comment by nemesifier** [comment]
dovrebbe essere risolto
