### ISSUE TITLE
raggruppare i file htdocs in cartelle diverse

### ISSUE THREAD

**Issue by nemesifier** [ninuxorg/nodogsplashninux#3]
i file della pagina web sono tutti raggruppati in "/htdocs/images" ma è difficile lavorarci. Si possono creare altre cartelle dentro /htdocs/images? Si possono creare altre cartelle al livello superiore di /htdocs/images, tipo /htdocs/fonts?

**Comment by zioproto** [comment]
penso di si, perché no ?

**Comment by nemesifier** [comment]
beh avevo pensato non fosse possibile dato che nel repository della sola splash page di gubi (che ho scaricato e provato in locale) i file sono raggruppati nella cartella media e a loro volta sono raggruppati in altre cartelle. Si può rimettere in quel modo lì? @claudyus che dici?

**Comment by gubi** [comment]
La mia logica è:
**.htaccess**
**index.***
**...** _(files di root)_
- **common/** (tutti i file richiesti da index)
  - **css/** (tutti i files css)
  - **js/** (tutti i files javascript)
  - **include/** (gli script di inclusione)
    - **_ajax/** (files richiamati via XHR)
    - **funcs/** (funzioni)
    - **lib/** (librerie)
    - **...**
  - **media/** (files multimediali, dentro cartella come estensione)
    - **fonts/** (font)
    - **img/** (immagini)
    - **swf/** (files flash)
    - **...**
  - **tpl/** (file di template)
  - **...**

Solitamente uso fare cartelle con le estensioni dei files già all'interno di "common/", tranne che per quanto riguarda gli script e i files multimediali che per chiare necessità sono invece raggruppati.
Mi trovo molto bene in questa maniera perché rimane sempre pulito, è intuitivo e facile da ricordare. :)
All'inizio avevo fatto così con la splash però naturalmente non funzionava, perciò per esigenza ho trasferito tutto dentro _$imagesdir_.

**Comment by claudyus** [comment]
@nemesisdesign si certo si può fare ma:
1) niente htaccess
2) evitiamo 1000 cartelle per una manciata di files

**Comment by nemesifier** [comment]
famo css, js, images, fonts e tpl

**Comment by gubi** [comment]
@nemesisdesign e @claudyus occhio che il mio era uno schema **generico** :)

**Comment by nemesifier** [comment]
sì l'avevo capito, per te le cartelle che ho proposto vanno bene?

**Comment by claudyus** [comment]
si appunto @gubi per quei 4 file che ci sono nn esageriamo

**Comment by claudyus** [comment]
2012/5/18 Federico Capoano:

> sì l'avevo capito, per te le cartelle che ho proposto vanno bene?

si si, per me meno parlare più codare :D
dentro openwrt se hai qualcosa di cui discutere prima commita e poi
chiedi commenti :)
(sarà la causa per cui non funzia?)

**Comment by gubi** [comment]
No problem, anzi perfetto ;)

**Comment by nemesifier** [comment]
Fatto nel branch minification https://github.com/ninuxorg/nodogsplashninux/commit/0ea28ca7a7e1f6eb8d42423b60bfbdb0469c9afb
